=== Navar02/TrabajoGAIJava/EjecutorXMLAHTML/input/erasmus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:eras="http://www.erasmusG4-6.org"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="http://www.erasmusG4-6.org"
    attributeFormDefault="qualified" vc:minVersion="1.1">
    
    <!-- Compendio de alumnos Erasmus -->
    <xs:element name="Compendium">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Alumno" type="eras:CurriculumAlumni" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Definición del elemento Curriculum para los alumnos -->
    <xs:complexType name="CurriculumAlumni">
        <xs:sequence>
            <xs:element ref="eras:PersonalInformation" maxOccurs="1"/>
            <xs:element name="OriginUniversity" type="eras:EducationTypeOrigin" minOccurs="1" maxOccurs="1"/>
            <xs:element name="ErasmusDestination" type="eras:EducationTypeDestination" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Experience" type="eras:ExperienceType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <!-- aserción para comprobar que origen no sea igual al destino -->
        <xs:assert test="OriginUniversity/Institution != ErasmusDestination/Institution"/>
    </xs:complexType>
    
    <xs:simpleType name="GenderType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="F"/>
            <xs:enumeration value="M"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Definición del tipo para información personal -->
    <xs:complexType name="PersonalInformationType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <!-- Restringir género a "F" o "M" -->
            <xs:element name="Gender" type="eras:GenderType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Email" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="Nationality" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Definición del tipo EducationTypeOrigin para definir el origen -->
    <xs:complexType name="EducationTypeOrigin">
        <xs:sequence>
            <xs:element name="Degree" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Institution" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <!-- Restringir número de créditos a un valor entero entre 0 y 240 -->
            <xs:element name="CreditsAchieved" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="240"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Definición del tipo EducationTypeDestination para definir la estancia -->
    <xs:complexType name="EducationTypeDestination">
        <xs:sequence>
            <xs:element name="Degree" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Institution" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="StartDate" type="xs:date" minOccurs="1" maxOccurs="1"/>
            <xs:element name="EndDate" type="xs:date" minOccurs="1" maxOccurs="1"/>
            <xs:element name="numberOfSubjects" type="xs:integer" minOccurs="1" maxOccurs="1"></xs:element>
            <!-- Nuevo elemento para asignaturas -->
            <xs:element name="Subject" minOccurs="1" maxOccurs="10">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="Credits" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        <xs:element name="Specialization" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <!-- Restricciones para las fechas de inicio y fin -->
        <xs:assert test="xs:date(EndDate) &gt;= xs:date(StartDate)"/>
        <xs:assert test="xs:date(StartDate) &gt;= xs:date(current-date())"/>    
        <xs:assert test="((12 * year-from-date(xs:date(EndDate)) + month-from-date(xs:date(EndDate))) - (12 * year-from-date(xs:date(StartDate)) + month-from-date(xs:date(StartDate))) = 4 and numberOfSubjects=5) or ((12 * year-from-date(xs:date(EndDate)) + month-from-date(xs:date(EndDate))) - (12 * year-from-date(xs:date(StartDate)) + month-from-date(xs:date(StartDate))) = 8 and numberOfSubjects=10)"/>
    </xs:complexType>
    
    <!-- Definición del tipo Experience para referencias laborales y posibles prácticas durante Erasmus -->
    <xs:complexType name="ExperienceType">
        <xs:sequence>
            <xs:element name="Position" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Employer" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="StartDate" type="xs:date" minOccurs="1" maxOccurs="1"/>
            <xs:element name="EndDate" type="xs:date" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <!-- Restricciones para las fechas de inicio y fin -->
        <xs:assert test="xs:date(EndDate) &gt;= xs:date(StartDate)"/>
        <xs:assert test="xs:date(StartDate) &gt;= xs:date(current-date())"/>
        <xs:assert test="((12 * year-from-date(xs:date(EndDate)) + month-from-date(xs:date(EndDate))) - (12 * year-from-date(xs:date(StartDate)) + month-from-date(xs:date(StartDate))) &lt;= 3) and ((12 * year-from-date(xs:date(EndDate)) + month-from-date(xs:date(EndDate))) - (12 * year-from-date(xs:date(StartDate)) + month-from-date(xs:date(StartDate))) >= 1)"/>
    </xs:complexType>
    
    <xs:element name="PersonalInformation" type="eras:PersonalInformationType"/>
    
</xs:schema>

=== Navar02/TrabajoGAIJava/EjecutorXMLAHTML/input/italia.xml
<eras:Compendium xmlns:eras="http://www.erasmusG4-6.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ita="http://www.italiaeras.org"
    xsi:schemaLocation="http://www.erasmusG4-6.org erasmus.xsd 
                        http://www.italiaeras.org italia.xsd">
    <Alumno>
        <ita:ExtPersonalInformation>
            <Name>John Doe</Name>
            <Gender>M</Gender>
            <Email>john.doe@example.com</Email>
            <Nationality>Spain</Nationality>
            <ita:PizzaPreference>Pizza al pastrami</ita:PizzaPreference>
            <ita:GelatoPreference>KKKKKKKKK Gelato</ita:GelatoPreference>
        </ita:ExtPersonalInformation>
        
        <OriginUniversity>
            <Degree>Bachelor of Science in Computer Science</Degree>
            <Institution>University of Example</Institution>
            <CreditsAchieved>120</CreditsAchieved>
        </OriginUniversity>
        <ita:ITA_EducationTypeDestination>
            
            <Degree>Computer Engineering</Degree>
            <Institution>University of Another Example</Institution>
            <StartDate>2024-09-01</StartDate>
            <EndDate>2025-05-31</EndDate>
            <numberOfSubjects>10</numberOfSubjects>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            
            <ita:Region>Abruzzo</ita:Region>
        </ita:ITA_EducationTypeDestination>
        <!-- Nuevo elemento ExperienceType -->
        <Experience>
            <Position></Position>
            <Employer></Employer>
            <StartDate>2024-09-01</StartDate>
            <EndDate>2024-12-30</EndDate>
        </Experience>
    </Alumno>
    
    <!-- Alumno 2 -->
    <Alumno>
        <ita:ExtPersonalInformation>
            <Name>Jane Smith</Name>
            <Gender>F</Gender>
            <Email>jane.smith@example.com</Email>
            <Nationality>Germany</Nationality>
            <ita:PizzaPreference>Pizza con todo</ita:PizzaPreference>
            <ita:GelatoPreference>Chocolate Gelato</ita:GelatoPreference>
            <Allergies>Alimentary</Allergies>
        </ita:ExtPersonalInformation>
        
        <OriginUniversity>
            <Degree>Bachelor of Arts in History</Degree>
            <Institution>University of Another Country</Institution>
            <CreditsAchieved>100</CreditsAchieved>
        </OriginUniversity>
        
        <ita:ITA_EducationTypeDestination>
            <Degree>History</Degree>
            <Institution>University of Yet Another Example</Institution>
            <StartDate>2024-09-01</StartDate>
            <EndDate>2025-05-30</EndDate>
            <numberOfSubjects>10</numberOfSubjects>
            <Subject>
                <Name>European History</Name>
                <Credits>4</Credits>
                <Description>An overview of European history.</Description>
                <Specialization>History</Specialization>
            </Subject>
            <!-- More subjects can be added here -->
        </ita:ITA_EducationTypeDestination>
        
        <Experience>
            <Position>Research Assistant</Position>
            <Employer>Historical Society</Employer>
            <StartDate>2024-09-01</StartDate>
            <EndDate>2024-12-31</EndDate>
        </Experience>
    </Alumno>
</eras:Compendium>

=== Navar02/TrabajoGAIJava/EjecutorXMLAHTML/input/alemania.xml
<eras:Compendium xmlns:eras="http://www.erasmusG4-6.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ale="http://www.erasmusG4-6/alemania.org"
    xsi:schemaLocation="http://www.erasmusG4-6.org erasmus.xsd http://www.erasmusG4-6/alemania.org alemania.xsd">
    <Alumno>
        <eras:PersonalInformation xsi:type="ale:DatosPersonalesAle">
            <Name>Erika Mustermann</Name>
            <Gender>F</Gender>
            <Email>Erika.Mustermann@example.com</Email>
            <Nationality>Deuschland</Nationality>
            <DIA>A123456789</DIA>
            <BirthDate>11-02-2000</BirthDate>
            <Estado>Berlin</Estado>
        </eras:PersonalInformation>
      <OriginUniversity xsi:type="ale:OriginUniversityAle">
            <Degree>Bachelor of Science in Computer Science</Degree>
            <Institution>University of Example</Institution>
            <CreditsAchieved>120</CreditsAchieved>
            <GradeType>Higher Technical Certificate</GradeType>
            <Extra>Online</Extra>
        </OriginUniversity>
        <eras:ErasmusDestination xsi:type="ale:EducationTypeDestinationAle">
            
            <Degree>Computer Engineering</Degree>
            <Institution>University of Another Example</Institution>
            <StartDate>2025-01-01</StartDate>
            <EndDate>2025-05-31</EndDate>
            <numberOfSubjects>5</numberOfSubjects>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Database Design</Name>
                <Credits>6</Credits>
                <Description>Deeper insight into database structures and management.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Web systems</Name>
                <Credits>6</Credits>
                <Description>An introduction to web pages, showing both front-end and back-end.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Computer architecture</Name>
                <Credits>6</Credits>
                <Description>An introduction into the hardware of computers.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Electronics applied to data processing</Name>
                <Credits>3</Credits>
                <Description>An advanced course into computer hardware focused on gathering data by sensors.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
        </eras:ErasmusDestination>
        <!-- Nuevo elemento ExperienceType -->
        <Experience>
            <Position>Becaria</Position>
            <Employer>CEO of MCDonalds</Employer>
            <StartDate>2024-09-01</StartDate>
            <EndDate>2024-12-30</EndDate>
        </Experience>
    </Alumno>
</eras:Compendium>

=== Navar02/TrabajoGAIJava/EjecutorXMLAHTML/input/erasmusGeneral.xml
<eras:Compendium xmlns:eras="http://www.erasmusG4-6.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.erasmusG4-6.org erasmus.xsd">
    <Alumno>
        <PersonalInformation>
            <Name>John Doe</Name>
            <Gender>M</Gender>
            <Email>john.doe@example.com</Email>
            <Nationality>US</Nationality>
        </PersonalInformation>
        <OriginUniversity>
            <Degree>Bachelor of Science in Computer Science</Degree>
            <Institution>University of Example</Institution>
            <CreditsAchieved>120</CreditsAchieved>
        </OriginUniversity>
        <ErasmusDestination>
            
            <Degree>Computer Engineering</Degree>
            <Institution>University of Another Example</Institution>
            <StartDate>2024-09-01</StartDate>
            <EndDate>2025-05-31</EndDate>
            <numberOfSubjects>10</numberOfSubjects>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
            <Subject>
                <Name>Data Structures</Name>
                <Credits>6</Credits>
                <Description>An introductory course to data structures.</Description>
                <Specialization>Computer Science</Specialization>
            </Subject>
        </ErasmusDestination>
        <!-- Nuevo elemento ExperienceType -->
        <Experience>
            <Position></Position>
            <Employer></Employer>
            <StartDate>2024-09-01</StartDate>
            <EndDate>2024-12-30</EndDate>
        </Experience>
    </Alumno>
</eras:Compendium>
